### ISSUE TITLE
Feedback on assignment 1 intro, data description and questions

### ISSUE THREAD

**Issue by dicook** [etc5521-2020/assignment-1-emu#1]
Good job getting  started on the first sections of assignment 1.

Its generally roughly drafted and will need cleaning and smoothing of your language and sentences. For example, "What does a winning beach volleyball player’s profile look like? Both male and female" is not a sentence. For you to think about: Do you think that a winning volleyball player's profile will look different? Why do you think that? Maybe something of this thinking culd be clear in the question too.

Your data has a lot of variables, so describing these is tricky. BUT there are actually just a few variables attacks, kills, blocks, ... but these are recorded multiply, for different players, ... so you can make a briefer more concise variable description. They can be grouped into different types too, like demographics of the player, statistics of the player.

It looks like your data might need some more tidying, because the column names indicate that it holds multiple variables thhat need further splitting out.

**Comment by jthoma48** [comment]
Thank you Di for your input. We will make the necessary changes.
